# Generated by Django 6.0.7 on 2026-08-30 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_content_template_block_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='site_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.sitesettings', verbose_name='Настройки сайта'),
        ),
    ]
