# Generated by Django 6.0.7 on 2026-08-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_site_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='content_template_block_3',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='content_text_template_block_3',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='homepage_advantages',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='homepage_advantages_h2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='homepage_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='homepage_text_h2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='img_template_alt_block_1',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='img_template_alt_block_2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='img_template_alt_block_3',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='img_template_block_1',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='img_template_block_2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='img_template_block_3',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='content_title_block_3',
            field=models.CharField(blank=True, verbose_name='Заголовок блока 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_text_block_1',
            field=models.TextField(blank=True, verbose_name='Текст блока 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_text_block_2',
            field=models.TextField(blank=True, verbose_name='Текст блока 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_text_block_3',
            field=models.TextField(blank=True, verbose_name='Текст блока 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_title_block_1',
            field=models.CharField(blank=True, verbose_name='Заголовок блока 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_title_block_2',
            field=models.CharField(blank=True, verbose_name='Заголовок блока 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='img_homepage_alt_block_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Alt для Img блока 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='img_homepage_alt_block_2',
            field=models.CharField(max_length=255, null=True, verbose_name='Alt для Img блока 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='img_homepage_alt_block_3',
            field=models.CharField(max_length=255, null=True, verbose_name='Alt для Img блока 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='img_homepage_block_1',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Img блока 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='img_homepage_block_2',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Img блока 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='img_homepage_block_3',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Img блока 3'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Номер телефона на сайте'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_description',
            field=models.TextField(blank=True, verbose_name='Description главной страницы'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_keywords',
            field=models.TextField(blank=True, verbose_name='Keywords главной страницы'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tittle главной страницы'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Производтво модульных зданий, блок контейнеров и металлоконструкций', max_length=255, verbose_name='Название сайта'),
        ),
    ]
