# Generated by Django 6.0.7 on 2026-08-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_sitesettings_content_template_block_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_email',
            field=models.CharField(blank=True, max_length=30, verbose_name='email на сайте'),
        ),
    ]
