# Generated by Django 6.0.7 on 2026-08-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sitesettings_default_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='content_title_block_3',
            field=models.CharField(blank=True, null=True, verbose_name='Заголовок блока 3'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_text_block_1',
            field=models.TextField(blank=True, null=True, verbose_name='Текст блока 1'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_text_block_2',
            field=models.TextField(blank=True, null=True, verbose_name='Текст блока 2'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_text_block_3',
            field=models.TextField(blank=True, null=True, verbose_name='Текст блока 3'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_title_block_1',
            field=models.CharField(blank=True, null=True, verbose_name='Заголовок блока 1'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_title_block_2',
            field=models.CharField(blank=True, null=True, verbose_name='Заголовок блока 2'),
        ),
    ]
