# Generated by Django 6.0.7 on 2026-08-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_topmenuitem_alter_faq_city_delete_servicefaq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepage',
            old_name='content',
            new_name='content_template_block_1',
        ),
        migrations.RenameField(
            model_name='servicetemplate',
            old_name='content_template',
            new_name='content_template_block_1',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='content_template_block_2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicepage',
            name='content_template_block_3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicepage',
            name='content_template_block_4',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicepage',
            name='img_template_alt_block_1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicepage',
            name='img_template_alt_block_2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicepage',
            name='img_template_alt_block_3',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicepage',
            name='img_template_alt_block_4',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicepage',
            name='img_template_block_1',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='img_template_block_2',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='img_template_block_3',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='img_template_block_4',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='content_template_block_2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='content_template_block_3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='content_template_block_4',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='img_template_alt_block_1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='img_template_alt_block_2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='img_template_alt_block_3',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='img_template_alt_block_4',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='img_template_block_1',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='img_template_block_2',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='img_template_block_3',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='img_template_block_4',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
