# Generated by Django 6.0.7 on 2026-08-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_rename_content_servicepage_content_template_block_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='content_template_block_1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='content_template_block_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='content_template_block_3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='content_template_block_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='img_template_alt_block_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='img_template_alt_block_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='img_template_alt_block_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='img_template_alt_block_4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='content_template_block_1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='content_template_block_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='content_template_block_3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='content_template_block_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='img_template_alt_block_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='img_template_alt_block_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='img_template_alt_block_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='img_template_alt_block_4',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
