# Generated by Django 6.0.7 on 2026-09-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_alter_servicepage_content_template_block_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='title_template_block_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='title_template_block_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='title_template_block_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='title_template_block_4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='title_template_block_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='title_template_block_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='title_template_block_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='title_template_block_4',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
