# Generated by Django 6.0.7 on 2026-08-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0015_city_choose_as_city_choose_as_h2_city_useful_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Города', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterField(
            model_name='city',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес офиса'),
        ),
        migrations.AlterField(
            model_name='city',
            name='choose_as',
            field=models.TextField(blank=True, verbose_name='Текст 1'),
        ),
        migrations.AlterField(
            model_name='city',
            name='choose_as_h2',
            field=models.TextField(blank=True, verbose_name='Заголовок текста 1'),
        ),
        migrations.AlterField(
            model_name='city',
            name='h1_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 Заголовок главной страницы'),
        ),
        migrations.AlterField(
            model_name='city',
            name='homepage_advantages',
            field=models.TextField(blank=True, verbose_name='Текст 4'),
        ),
        migrations.AlterField(
            model_name='city',
            name='homepage_advantages_h2',
            field=models.TextField(blank=True, verbose_name='Заголовок текста 4'),
        ),
        migrations.AlterField(
            model_name='city',
            name='homepage_text',
            field=models.TextField(blank=True, verbose_name='Текст 3'),
        ),
        migrations.AlterField(
            model_name='city',
            name='homepage_text_h2',
            field=models.TextField(blank=True, verbose_name='Заголовок текста 3'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Город активен?'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_rented',
            field=models.BooleanField(default=False, verbose_name='Город сдан в аренду?'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_oblast',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название области'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_oblast_where',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название области - где?'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_where',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название города - где?'),
        ),
        migrations.AlterField(
            model_name='city',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='city',
            name='price_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='city',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description главной страницы'),
        ),
        migrations.AlterField(
            model_name='city',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords главной страницы'),
        ),
        migrations.AlterField(
            model_name='city',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title главной страницы'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='city',
            name='useful',
            field=models.TextField(blank=True, verbose_name='Текст 2'),
        ),
        migrations.AlterField(
            model_name='city',
            name='useful_h2',
            field=models.TextField(blank=True, verbose_name='Заголовок текста 2'),
        ),
    ]
