# Generated by Django 6.0.7 on 2026-08-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0016_alter_city_options_alter_city_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='email'),
        ),
    ]
