# Generated by Django 6.0.7 on 2026-08-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0017_city_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='choose_as',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 1'),
        ),
        migrations.AlterField(
            model_name='city',
            name='choose_as_h2',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок текста 1'),
        ),
        migrations.AlterField(
            model_name='city',
            name='homepage_advantages',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 4'),
        ),
        migrations.AlterField(
            model_name='city',
            name='homepage_advantages_h2',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок текста 4'),
        ),
        migrations.AlterField(
            model_name='city',
            name='homepage_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 3'),
        ),
        migrations.AlterField(
            model_name='city',
            name='homepage_text_h2',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок текста 3'),
        ),
        migrations.AlterField(
            model_name='city',
            name='useful',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 2'),
        ),
        migrations.AlterField(
            model_name='city',
            name='useful_h2',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок текста 2'),
        ),
    ]
