# Generated by Django 6.0.7 on 2026-08-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0018_alter_city_choose_as_alter_city_choose_as_h2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='homepage_text_img',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='city',
            name='homepage_text_img_alt',
            field=models.CharField(max_length=255, null=True, verbose_name='Alt Изображения 2'),
        ),
        migrations.AddField(
            model_name='city',
            name='img_choose_as',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='city',
            name='img_choose_as_alt',
            field=models.CharField(max_length=255, null=True, verbose_name='Alt Изображения 1'),
        ),
        migrations.AddField(
            model_name='city',
            name='img_useful',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='city',
            name='img_useful_alt',
            field=models.CharField(max_length=255, null=True, verbose_name='Alt Изображения 2'),
        ),
    ]
