# Generated by Django 6.0.7 on 2026-09-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0019_city_homepage_text_img_city_homepage_text_img_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='homepage_text_img',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Изображение 3'),
        ),
        migrations.AlterField(
            model_name='city',
            name='homepage_text_img_alt',
            field=models.CharField(max_length=255, null=True, verbose_name='Alt Изображения 3'),
        ),
    ]
